version: "3"

services:
  redis:
    container_name: "redis"
    ports:
      - "6379:6379"
    build:
      context: ./redis/
    volumes:
      - redis_data:/data

  app:
    container_name: "app"
    build:
      context: ./node/
    depends_on:
      - redis

volumes:
  redis_data:
